server:
  port: 8761

spring:
  application:
    name: service-registry
  security:
    user:
      name: eureka
      password: eureka123

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:${server.port}/eureka/
